//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceCalculadora.CalculadoraWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://control/", ConfigurationName="CalculadoraWebService.Calculadora")]
    public interface Calculadora {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://control/Calculadora/calcularComplexidadeRequest", ReplyAction="http://control/Calculadora/calcularComplexidadeResponse")]
        WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponse calcularComplexidade(WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://control/Calculadora/calcularComplexidadeRequest", ReplyAction="http://control/Calculadora/calcularComplexidadeResponse")]
        System.Threading.Tasks.Task<WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponse> calcularComplexidadeAsync(WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calcularComplexidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calcularComplexidade", Namespace="http://control/", Order=0)]
        public WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequestBody Body;
        
        public calcularComplexidadeRequest() {
        }
        
        public calcularComplexidadeRequest(WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class calcularComplexidadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arestas;
        
        public calcularComplexidadeRequestBody() {
        }
        
        public calcularComplexidadeRequestBody(int nos, int arestas) {
            this.nos = nos;
            this.arestas = arestas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calcularComplexidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calcularComplexidadeResponse", Namespace="http://control/", Order=0)]
        public WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponseBody Body;
        
        public calcularComplexidadeResponse() {
        }
        
        public calcularComplexidadeResponse(WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class calcularComplexidadeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public calcularComplexidadeResponseBody() {
        }
        
        public calcularComplexidadeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraChannel : WebServiceCalculadora.CalculadoraWebService.Calculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraClient : System.ServiceModel.ClientBase<WebServiceCalculadora.CalculadoraWebService.Calculadora>, WebServiceCalculadora.CalculadoraWebService.Calculadora {
        
        public CalculadoraClient() {
        }
        
        public CalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponse WebServiceCalculadora.CalculadoraWebService.Calculadora.calcularComplexidade(WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest request) {
            return base.Channel.calcularComplexidade(request);
        }
        
        public string calcularComplexidade(int nos, int arestas) {
            WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest inValue = new WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest();
            inValue.Body = new WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequestBody();
            inValue.Body.nos = nos;
            inValue.Body.arestas = arestas;
            WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponse retVal = ((WebServiceCalculadora.CalculadoraWebService.Calculadora)(this)).calcularComplexidade(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponse> WebServiceCalculadora.CalculadoraWebService.Calculadora.calcularComplexidadeAsync(WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest request) {
            return base.Channel.calcularComplexidadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeResponse> calcularComplexidadeAsync(int nos, int arestas) {
            WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest inValue = new WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequest();
            inValue.Body = new WebServiceCalculadora.CalculadoraWebService.calcularComplexidadeRequestBody();
            inValue.Body.nos = nos;
            inValue.Body.arestas = arestas;
            return ((WebServiceCalculadora.CalculadoraWebService.Calculadora)(this)).calcularComplexidadeAsync(inValue);
        }
    }
}
